landing1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('page1/', include('page1.urls')),
]

page1/urls.py
from django.urls import path

from . import views


app_name = 'page1'

urlpatterns = [
    path('', views.index, name='index'),
    path('team', views.team, name='team'),
]

page1/models.py
from django.db import models

# Create your models here.

page1/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView
from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'index.html', context)


def team(request):
    context = {}
    return render(request, 'team.html', context)

page1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Астор Медікал{% endblock %}</title>
    {% load static %}
    <link href="{% static 'images/style.css' %}" rel="stylesheet" type="text/css"/>
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
    <script crossorigin="anonymous" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/65d9107569.js" crossorigin="anonymous"></script>
    <meta content="width=device-width, initial-scale=1" name="viewport">

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="navbar-brand" href="{% url 'page1:index' %}">Астор Медікал</a>
    <button aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation"
            class="navbar-toggler" data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Про нас </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'page1:team' %}">Команда </a>
            </li>
        </ul>
    </div>
</nav>

{% block body %}
{% endblock %}

<footer class="footer-distributed">
    <div class="footer-left">
        <div>
           <h6 class="font-small font-weight-normal">
               <span><i class="fa fa-map-marker"></i>Адресa:</span>
           </h6>
                <p> Кіровоградський район
                 <br />с. Соколівське 25005
                <br />вул. Українська, 67
                    <br />25006</p>
        </div>
    </div>
    <div class="footer-center">
        <h6>
            <h6 class="font-small font-weight-normal"><i class="fa fa-clock-o" aria-hidden="true"></i>Розклад роботи</h6>
            <ul>
                <p><span>Пн-Пт: 9:00–17:00</span></p>
                <p><span>Сб-Нд: 11:00–15:00</span></p>
            </ul>
        </div>
    </div>
    <div class="footer-right">
        <div>
            <span><i class="fa fa-phone"></i>+38 (097) 807-98-28</span>
        </div>
    </div>
    <div class="footer-copyright text-center font-italic">designed by Julie © 2020</div>
</footer>
</body>
</html>

page1/templates/home.html
!<!--{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class = "starter-template">
    <h2>Про нас</h2>
    <p class="lead">


    </p>
</div>
{% endblock%} -->

page1/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="main">
    <div class="header-h1">
    <h1>АСТОР МЕДІКАЛ</h1>
    </div>
<div class="img_container text-justify">
    <img src="/static/images/background.jpg"  class="img-fluid"/>
    <p>У своїй роботі ми спираємося на всесвітньо визнані технології та рішення відомих медичних корпорацій.</p>
    <p>Наші фахівці надають повну підтримку щодо медичного забезпечення необхідного для діалізної терапії та служби крові у повній відповідності до міжнародних стандартів.</p>
    <p>Мета нашої компанії – надання якісного та надійного фармацевтичного обладнання, враховуючи соціальні потреби суспільства. Саме соціальний компонент робить нашу діяльність унікальною для вітчизняної фармацевтики.</p>
</div>
</div>
{% endblock %}

page1/templates/team.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="main">
    <div class="header-h1">
    <h1>Команда</h1>
    </div>
<div class="img_container text-justify">
    <img src="/static/images/team_background.jpg"  class="img-fluid"/>
    <p>Наша команда складається з висококваліфікованих спеціалістів, які роблять все можливе задля розвитку охорони здоров’я та добробуту українців.</p>
    <p>Командна робота - гарантія досягнення нашої мети щодо покращення якості життя людей. </p>
</div>
</div>
{% endblock %}